### ISSUE TITLE
Desired functionality of roll_sd when center is provided

### ISSUE THREAD

**Issue by ckatsulis** [jjf234/roll#5] opened 2017-12-01 19:27 UTC
I have written a couple unit tests to ensure that roll_scale matches the result of the 4 permutations of the way `center` and `scale` can be provided roll_scale.

The four tests are as follows:

1.  roll_scale(data, 60, scale = T, center = T)
2.  roll_scale(data, 60, scale = T, center = F)
3.  roll_scale(data, 60, scale = F, center = T)
4.  roll_scale(data, 60, scale = F, center = F)

These need to be equivalent to the following calls in order:
1.  (data - roll_mean(data,60)) / roll_sd(data,60)
2.  data / roll_sd(data,60)
3.  data - roll_mean(data,60)
4.  data  (or possibly data with nas populated in the first 59 entries)
```
require(roll)
require(testthat)

testthat::expect_equivalent(roll_scale(data, 60, scale = T, center = T),(data - roll_mean(data,60)) / roll_sd(data,60))
testthat::expect_equivalent(roll_scale(data, 60, scale = T, center = F),data / roll_sd(data,60))
testthat::expect_equivalent(roll_scale(data, 60, scale = F, center = T),data - roll_mean(data,60))
testthat::expect_equivalent(roll_scale(data, 60, scale = F, center = F), data)
```
The tests fail in the following ways (only one fail truthfully  in case #2)
```
> testthat::expect_equivalent(roll_scale(data, 60, scale = T, center = T),(data - roll_mean(data,60)) / roll_sd(data,60))
> testthat::expect_equivalent(roll_scale(data, 60, scale = T, center = F),data / roll_sd(data,60))
Error: roll_scale(data, 60, scale = T, center = F) not equivalent to data/roll_sd(data, 60).
Mean relative difference: 0.006639237
> testthat::expect_equivalent(roll_scale(data, 60, scale = F, center = T),data - roll_mean(data,60))
> testthat::expect_equivalent(roll_scale(data, 60, scale = F, center = F), data)
Error: roll_scale(data, 60, scale = F, center = F) not equivalent to `data`.
'is.NA' value mismatch: 0 in current 59 in target
```

Please load with `dget`.
[**rollDataExample.txt**](https://github.com/jjf234/roll/files/1522714/rollDataExample.txt)

**Comment by jjf234** [comment] 2017-12-09 14:23
In the second test case you simply have to set the `center` argument in `roll_sd` to `FALSE` too. Maybe the documentation from the `scale` function can clear things up:

> If scale is TRUE then scaling is done by dividing the (centered) columns of x by their standard deviations if center is TRUE, and the root mean square otherwise.
>
>The root-mean-square for a (possibly centered) column is defined as sqrt(sum(x^2)/(n-1)),
where x is a vector of the non-missing values and n is the number of non-missing values. In the case center = TRUE, this is the same as the standard deviation, but in general it is not. (To scale by the standard deviations without centering, use scale(x, center = FALSE, scale = apply(x, 2, sd, na.rm = TRUE)).)

My goal is to be consistent with the base `scale` function so when I roll it the four test cases match the behavior of the `roll_scale` function as intended:
```
library(roll)
library(testthat)
library(xts)

r_scale <- function(data, center = TRUE, scale = TRUE) {
  return(scale(data, center = center, scale = scale)[length(data)])
}

> expect_equivalent(roll_scale(data, 60, scale = T, center = T),
+                   rollapplyr(data, 60, r_scale, scale = T, center = T))
> expect_equivalent(roll_scale(data, 60, scale = T, center = F),
+                   rollapplyr(data, 60, r_scale, scale = T, center = F))
> expect_equivalent(roll_scale(data, 60, scale = F, center = T),
+                   rollapplyr(data, 60, r_scale, scale = F, center = T))
> expect_equivalent(roll_scale(data, 60, scale = F, center = F),
+                   rollapplyr(data, 60, r_scale, scale = F, center = F))
```
Anyway I will update and clarify the documentation for future users to avoid confusion before closing it out.

**Closed** 2017-12-11 11:00 UTC
