### ISSUE TITLE
Inconsistent behavior of roll_sd from 32bit and 64bit R

### ISSUE THREAD

**Issue by shaojl7** [jjf234/roll#8] opened 2018-02-26 10:17 UTC
I am using `roll_scale` function on a `xts` object, and find there is inconsistent behavior from 32bit or 64bit R  version. 

Below is a sample I am referring to

**On 32-bit R**
```r
library(xts)
library(roll)
sample <- structure(c(7.145, 7.145, 7.145, 7.145, 7.145, 7.145, 7.3684, 
                      7.3684, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 
                      7.26, 7.26, 7.26), class = c("xts", "zoo"), .indexCLASS = "Date", tclass = "Date", .indexTZ = "UTC", tzone = "UTC", index = structure(c(1507507200, 
                                                                                                                                                              1507593600, 1507680000, 1507766400, 1507852800, 1508112000, 1508198400, 
                                                                                                                                                              1508284800, 1508371200, 1508457600, 1508716800, 1508803200, 1508889600, 
                                                                                                                                                              1508976000, 1509062400, 1509321600, 1509408000, 1509494400, 1509580800, 
                                                                                                                                                              1509667200), tzone = "UTC", tclass = "Date"), .Dim = c(20L, 1L
                                                                                                                                                              ), .Dimnames = list(NULL, "value"))
roll_scale(sample, 3)
# value
# 2017-10-09         NA
# 2017-10-10         NA
# 2017-10-11        NaN
# 2017-10-12        NaN
# 2017-10-13        NaN
# 2017-10-16        NaN
# 2017-10-17  1.1547005
# 2017-10-18  0.5773503
# 2017-10-19 -1.1547005
# 2017-10-20 -0.5773503
# 2017-10-23        NaN
# 2017-10-24        NaN
# 2017-10-25        NaN
# 2017-10-26        NaN
# 2017-10-27        NaN
# 2017-10-30        NaN
# 2017-10-31        NaN
# 2017-11-01        NaN
# 2017-11-02        NaN
# 2017-11-03        NaN

sessionInfo()
# R version 3.4.2 (2017-09-28)
# Platform: i386-w64-mingw32/i386 (32-bit)
# Running under: Windows 7 x64 (build 7601) Service Pack 1
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252
# [3] LC_MONETARY=English_Singapore.1252 LC_NUMERIC=C
# [5] LC_TIME=English_Singapore.1252
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base
# 
# other attached packages:
#   [1] roll_1.0.7 xts_0.10-1 zoo_1.8-1
# 
# loaded via a namespace (and not attached):
#   [1] compiler_3.4.2        Rcpp_0.12.14          grid_3.4.2
# [4] RcppParallel_4.3.20.2 lattice_0.20-35
```

**On 64-bit R**
```r
library(xts)
library(roll)
sample <- structure(c(7.145, 7.145, 7.145, 7.145, 7.145, 7.145, 7.3684, 
                      7.3684, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 7.26, 
                      7.26, 7.26, 7.26), class = c("xts", "zoo"), .indexCLASS = "Date", tclass = "Date", .indexTZ = "UTC", tzone = "UTC", index = structure(c(1507507200, 
                                                                                                                                                              1507593600, 1507680000, 1507766400, 1507852800, 1508112000, 1508198400, 
                                                                                                                                                              1508284800, 1508371200, 1508457600, 1508716800, 1508803200, 1508889600, 
                                                                                                                                                              1508976000, 1509062400, 1509321600, 1509408000, 1509494400, 1509580800, 
                                                                                                                                                              1509667200), tzone = "UTC", tclass = "Date"), .Dim = c(20L, 1L
                                                                                                                                                              ), .Dimnames = list(NULL, "value"))
roll_scale(sample, 3)
# value
# 2017-10-09         NA
# 2017-10-10         NA
# 2017-10-11        NaN
# 2017-10-12        NaN
# 2017-10-13        NaN
# 2017-10-16        NaN
# 2017-10-17  1.1547005
# 2017-10-18  0.5773503
# 2017-10-19 -1.1547005
# 2017-10-20 -0.5773503
# 2017-10-23 -0.8164966
# 2017-10-24 -0.8164966
# 2017-10-25 -0.8164966
# 2017-10-26 -0.8164966
# 2017-10-27 -0.8164966
# 2017-10-30 -0.8164966
# 2017-10-31 -0.8164966
# 2017-11-01 -0.8164966
# 2017-11-02 -0.8164966
# 2017-11-03 -0.8164966

sessionInfo()
# R version 3.4.2 (2017-09-28)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 7 x64 (build 7601) Service Pack 1
# 
# Matrix products: default
# 
# locale:
#   [1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252
# [3] LC_MONETARY=English_Singapore.1252 LC_NUMERIC=C
# [5] LC_TIME=English_Singapore.1252
# 
# attached base packages:
#   [1] stats     graphics  grDevices utils     datasets  methods   base
# 
# other attached packages:
#   [1] roll_1.0.7 xts_0.10-1 zoo_1.8-1
# 
# loaded via a namespace (and not attached):
#   [1] compiler_3.4.2        Rcpp_0.12.14          grid_3.4.2
# [4] RcppParallel_4.3.20.2 lattice_0.20-35
```

In the `sample` xts object, the values since 2017-10-19 are the same. 32-bit R would give me all NA values since then.

**Comment by jjf234** [comment] 2018-03-03 16:47
Thanks for the report. Looks like the issue is related to floating point arithmetic. If you run the `roll_var` function, i.e. the denominator in `roll_scale`, you’ll get a value near zero in the 64-bit version and zero in the 32-bit version (which is why you then get `NaN` in `roll_scale` as expected). Interestingly, in the 64-bit version, the numerator is also near zero (since it is centered and the input values are unchanged), so then the `scale` division results in the value of `-0.8164966`. The issue was resolved by changing the variable types in the worker functions from `double` to `long double` and is now fixed in the development version:

```
# install.packages("devtools")
devtools::install_github("jjf234/roll")
```

**Closed by jjf234** 2018-03-03 16:47 UTC
Labels: bug
